package server

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Self-signed TLS (`--tls self-signed`): a key pair and certificate are
// generated on first start under <root>/tls, reused afterwards, and
// replaced only when expired. Clients trust the certificate file directly
// (aws --ca-bundle, boto3 verify=, curl --cacert) or pin the fingerprint
// printed at start.

const (
	selfSignedDir      = "tls"
	selfSignedCert     = "tls.crt"
	selfSignedKey      = "tls.key"
	selfSignedValidity = 825 * 24 * time.Hour // the longest Apple platforms accept for a user-trusted certificate
	selfSignedWarnDays = 30
)

// selfSigned is the loaded or generated certificate with what to log.
type selfSigned struct {
	cert        tls.Certificate
	leaf        *x509.Certificate
	certPath    string
	created     bool     // generated by this call
	renewed     bool     // an expired certificate was replaced
	missing     []string // names the server serves that the certificate does not cover
	fingerprint string
}

// selfSignedNames lists the names and addresses clients may use to reach
// this server: localhost, the host name, every non-loopback interface
// address, the configured domains with their bucket wildcards, and the
// host part of the listen address when it names one.
func selfSignedNames(address string, domains []string) (dns []string, ips []net.IP) {
	seen := map[string]bool{}
	addDNS := func(n string) {
		n = strings.ToLower(strings.TrimSpace(n))
		if n != "" && !seen["d:"+n] {
			seen["d:"+n] = true
			dns = append(dns, n)
		}
	}
	addIP := func(ip net.IP) {
		if ip != nil && !seen["i:"+ip.String()] {
			seen["i:"+ip.String()] = true
			ips = append(ips, ip)
		}
	}
	addDNS("localhost")
	if h, err := os.Hostname(); err == nil {
		addDNS(h)
	}
	addIP(net.ParseIP("127.0.0.1"))
	addIP(net.ParseIP("::1"))
	if addrs, err := net.InterfaceAddrs(); err == nil {
		for _, a := range addrs {
			if ipn, ok := a.(*net.IPNet); ok && !ipn.IP.IsLoopback() && !ipn.IP.IsLinkLocalUnicast() {
				addIP(ipn.IP)
			}
		}
	}
	if host, _, err := net.SplitHostPort(address); err == nil && host != "" {
		if ip := net.ParseIP(host); ip != nil {
			if !ip.IsUnspecified() {
				addIP(ip)
			}
		} else {
			addDNS(host)
		}
	}
	for _, d := range domains {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		addDNS(d)
		addDNS("*." + d)
	}
	return dns, ips
}

// loadOrCreateSelfSigned returns the certificate under dir, generating it
// when absent and regenerating it when expired.
func loadOrCreateSelfSigned(dir, address string, domains []string, now time.Time) (*selfSigned, error) {
	certPath := filepath.Join(dir, selfSignedCert)
	keyPath := filepath.Join(dir, selfSignedKey)
	dns, ips := selfSignedNames(address, domains)
	s := &selfSigned{certPath: certPath}
	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	switch {
	case err == nil:
		leaf, err := x509.ParseCertificate(cert.Certificate[0])
		if err != nil {
			return nil, fmt.Errorf("tls: %s: %w", certPath, err)
		}
		if now.Before(leaf.NotAfter) {
			s.cert, s.leaf = cert, leaf
			s.missing = uncovered(leaf, dns, ips)
			s.fingerprint = certFingerprint(leaf)
			return s, nil
		}
		s.renewed = true
	case errors.Is(err, os.ErrNotExist):
		s.created = true
	default:
		return nil, fmt.Errorf("tls: %s: %w", certPath, err)
	}
	cert, leaf, err := generateSelfSigned(dns, ips, now, selfSignedValidity)
	if err != nil {
		return nil, err
	}
	if err := writeSelfSigned(dir, cert); err != nil {
		return nil, err
	}
	s.cert, s.leaf, s.fingerprint = cert, leaf, certFingerprint(leaf)
	return s, nil
}

// generateSelfSigned makes an ECDSA P-256 key and a self-signed
// certificate that can also act as its own trust anchor (CA:TRUE, as
// `openssl req -x509` produces), so clients can pass the file as a CA bundle.
func generateSelfSigned(dns []string, ips []net.IP, now time.Time, validity time.Duration) (tls.Certificate, *x509.Certificate, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return tls.Certificate{}, nil, err
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 127))
	if err != nil {
		return tls.Certificate{}, nil, err
	}
	cn := "OpenS3 self-signed"
	if len(dns) > 1 {
		cn += " (" + dns[1] + ")" // the host name
	}
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: cn, Organization: []string{"OpenS3"}},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(validity),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true,
		DNSNames:              dns,
		IPAddresses:           ips,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return tls.Certificate{}, nil, err
	}
	leaf, err := x509.ParseCertificate(der)
	if err != nil {
		return tls.Certificate{}, nil, err
	}
	return tls.Certificate{Certificate: [][]byte{der}, PrivateKey: key, Leaf: leaf}, leaf, nil
}

// writeSelfSigned stores the pair under dir: the certificate world-readable
// (clients copy it), the key owner-only; both written atomically.
func writeSelfSigned(dir string, cert tls.Certificate) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	kb, err := x509.MarshalECPrivateKey(cert.PrivateKey.(*ecdsa.PrivateKey))
	if err != nil {
		return err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: kb})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Certificate[0]})
	if err := writeFileAtomic(filepath.Join(dir, selfSignedKey), keyPEM, 0o600); err != nil {
		return err
	}
	return writeFileAtomic(filepath.Join(dir, selfSignedCert), certPEM, 0o644)
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	tmp := path + ".tmp"
	f, err := os.OpenFile(tmp, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Sync(); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}

// uncovered lists the wanted names the certificate does not contain.
func uncovered(leaf *x509.Certificate, dns []string, ips []net.IP) []string {
	var out []string
	for _, d := range dns {
		if leaf.VerifyHostname(d) != nil {
			out = append(out, d)
		}
	}
	for _, ip := range ips {
		if leaf.VerifyHostname(ip.String()) != nil {
			out = append(out, ip.String())
		}
	}
	sort.Strings(out)
	return out
}

// certFingerprint is the SHA-256 of the DER certificate as colon-separated
// hex, the form browsers and `openssl x509 -fingerprint -sha256` show.
func certFingerprint(leaf *x509.Certificate) string {
	sum := sha256.Sum256(leaf.Raw)
	h := strings.ToUpper(hex.EncodeToString(sum[:]))
	parts := make([]string, 0, len(h)/2)
	for i := 0; i < len(h); i += 2 {
		parts = append(parts, h[i:i+2])
	}
	return strings.Join(parts, ":")
}

// names renders the certificate's subject alternative names for logs.
func (s *selfSigned) names() []string {
	out := append([]string(nil), s.leaf.DNSNames...)
	for _, ip := range s.leaf.IPAddresses {
		out = append(out, ip.String())
	}
	return out
}
