#!/usr/bin/env python3
"""Summarise an AWS CLI suite run (tests/awscli/suite.sh) for OpenS3.

Usage: report.py --results tests/awscli/results [--markdown docs/AWSCLI.md]
                 [--version "aws-cli/2.x ..."] [--mode docker|native]
                 [--image amazon/aws-cli:TAG] [--duration SECONDS]

Reads results/results.tsv (one case per line: name, service, command, kind,
status, detail) and results/help-<service>.txt (the `aws <service> help`
pages, from which the full command lists are parsed) and writes a Markdown
report with a per-service table of every CLI command and its status:

  passed               at least one case ran it and every case passed
  failed               some case ran it and failed
  expected-unsupported only `unsupported` cases (expected error) ran it, all passed
  not exercised        no case used the command

Exit status is 1 on any failed case or when the results are unreadable.
Stdlib only.
"""
import argparse
import collections
import datetime
import os
import re
import sys

SERVICES = ["s3", "s3api", "iam", "sts", "transport"]
# Client-side commands that make no request of their own.
CLIENT_SIDE = {"help", "wizard"}

# Why a command is deliberately not exercised (shown in the report).
NOT_EXERCISED_REASONS = {
    ("s3api", "write-get-object-response"): "S3 Object Lambda only: the CLI sends it to the host `<request-route>.<endpoint>`, which cannot reach OpenS3",
}
UNSUPPORTED_NOTE = ("These concern AWS-only features (roles, instance "
                    "profiles, MFA, SAML/OIDC providers, server certificates, signing/SSH keys, service-specific "
                    "credentials, credential reports, organisations, delegation requests); OpenS3 answers all of them "
                    "with `InvalidAction` and the suite runs a representative subset as expected-unsupported.")

ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")
OVERSTRIKE = re.compile(r".\x08")


def parse_help(path):
    """Command names from the AVAILABLE COMMANDS section of `aws <svc> help`."""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return []
    text = OVERSTRIKE.sub("", ANSI.sub("", text))
    _, _, tail = text.partition("AVAILABLE COMMANDS")
    if not tail:
        return []
    cmds = []
    for line in tail.splitlines():
        m = re.match(r"^\s*(?:\+?o|\*|-)\s+([a-z0-9][a-z0-9-]*)\s*$", line)
        if m:
            cmds.append(m.group(1))
        elif re.match(r"^\S", line) and cmds:
            break  # next top-level section
    return cmds


def load_results(path):
    cases = []
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) < 5:
                raise ValueError(f"{path}:{n}: expected 6 tab-separated fields")
            parts += [""] * (6 - len(parts))
            name, svc, cmd, kind, status, detail = parts[:6]
            cases.append({"name": name, "svc": svc, "cmd": cmd, "kind": kind, "status": status, "detail": detail})
    return cases


def command_status(cases):
    if not cases:
        return "not exercised"
    if any(c["status"] != "PASS" for c in cases):
        return "failed"
    if all(c["kind"] == "unsupported" for c in cases):
        return "expected-unsupported"
    return "passed"


def build_matrix(cases, help_lists):
    """{svc: [(cmd, status, [cases])]} over the union of help list and results."""
    by_cmd = collections.defaultdict(list)
    for c in cases:
        by_cmd[(c["svc"], c["cmd"])].append(c)
    matrix = collections.OrderedDict()
    for svc in SERVICES:
        cmds = [c for c in help_lists.get(svc, []) if c not in CLIENT_SIDE]
        extra = sorted({cmd for (s, cmd) in by_cmd if s == svc and cmd not in cmds})
        rows = []
        for cmd in cmds + extra:
            cs = by_cmd.get((svc, cmd), [])
            rows.append((cmd, command_status(cs), cs))
        matrix[svc] = rows
    return matrix


def md_escape(s):
    return s.replace("|", "\\|").replace("`", "'")


def write_markdown(path, cases, matrix, help_lists, args):
    npass = sum(1 for c in cases if c["status"] == "PASS")
    nfail = len(cases) - npass
    lines = []
    lines.append("# AWS CLI compatibility report")
    lines.append("")
    lines.append("Generated by `tests/awscli/run.sh` (`make awscli`) — do not edit by hand.")
    lines.append("")
    lines.append(f"- CLI: `{args.version or 'unknown'}`")
    if args.mode == "docker":
        lines.append(f"- run mode: Docker image `{args.image}` (one container for the whole suite, `--network host`)")
    else:
        lines.append(f"- run mode: native binary `{args.image}`")
    lines.append(f"- run date: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    if args.duration:
        d = int(args.duration)
        lines.append(f"- wall time: {d // 60}m{d % 60:02d}s")
    lines.append("")
    lines.append(f"**{npass} cases passed, {nfail} failed ({len(cases)} run).**")
    lines.append("")
    lines.append("A *case* is one CLI invocation with an expectation (exit 0, a specific "
                 "error code, or a specific `--query` result). A *command* is an `aws <service> <command>` "
                 "as listed by `aws <service> help`; its status is **passed** when every case that used it "
                 "passed, **failed** when any did, **expected-unsupported** when the only cases that used it "
                 "expect the documented error (OpenS3 does not implement it), and **not exercised** when no case used it.")
    lines.append("")
    lines.append("## Summary by service")
    lines.append("")
    lines.append("| Service | Commands | Passed | Failed | Expected-unsupported | Not exercised | Cases |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for svc, rows in matrix.items():
        cnt = collections.Counter(st for _, st, _ in rows)
        ncases = sum(1 for c in cases if c["svc"] == svc)
        lines.append(f"| {svc} | {len(rows)} | {cnt['passed']} | {cnt['failed']} | {cnt['expected-unsupported']} | {cnt['not exercised']} | {ncases} |")
    lines.append("")
    failed = [c for c in cases if c["status"] != "PASS"]
    if failed:
        lines.append("## Failed cases")
        lines.append("")
        lines.append("| Case | Command | Expectation | Detail |")
        lines.append("|---|---|---|---|")
        for c in failed:
            lines.append(f"| `{c['name']}` | `{c['svc']} {c['cmd']}` | {c['kind']} | {md_escape(c['detail'])} |")
        lines.append("")
    for svc, rows in matrix.items():
        lines.append(f"## aws {svc}")
        lines.append("")
        if svc == "transport":
            lines.append("Scenarios rather than commands: the CLI against a TLS server and a plain server with matching and mismatching endpoint schemes, and the browser side of the TLS port (`tests/awscli/transport.sh`).")
        elif not help_lists.get(svc):
            lines.append(f"(`aws {svc} help` output missing — command list taken from the results only)")
            lines.append("")
        lines.append("| Command | Status | Cases |")
        lines.append("|---|---|---|")
        for cmd, st, cs in rows:
            names = ", ".join(f"`{c['name']}`" for c in cs)
            mark = {"passed": "passed", "failed": "**FAILED**", "expected-unsupported": "expected-unsupported", "not exercised": "not exercised"}[st]
            lines.append(f"| `{cmd}` | {mark} | {names} |")
        lines.append("")
    lines.append("## Not exercised")
    lines.append("")
    lines.append("Commands the CLI offers that no case runs.")
    lines.append("")
    for svc, rows in matrix.items():
        missing = [cmd for cmd, st, _ in rows if st == "not exercised"]
        if not missing:
            continue
        explained = [(m, NOT_EXERCISED_REASONS[(svc, m)]) for m in missing if (svc, m) in NOT_EXERCISED_REASONS]
        rest = [m for m in missing if (svc, m) not in NOT_EXERCISED_REASONS]
        for m, why in explained:
            lines.append(f"- **{svc}** `{m}`: {why}")
        if rest:
            lines.append(f"- **{svc}** ({len(rest)}): " + ", ".join(f"`{m}`" for m in rest))
            if svc == "iam":
                lines.append(f"  {UNSUPPORTED_NOTE}")
    if not any(st == "not exercised" for rows in matrix.values() for _, st, _ in rows):
        lines.append("- none")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, help="results directory (results.tsv, help-*.txt)")
    ap.add_argument("--markdown")
    ap.add_argument("--version", default="")
    ap.add_argument("--mode", default="docker")
    ap.add_argument("--image", default="")
    ap.add_argument("--duration", type=float, default=0)
    args = ap.parse_args()

    try:
        cases = load_results(os.path.join(args.results, "results.tsv"))
    except (OSError, ValueError) as e:
        print(f"report: cannot read results: {e}", file=sys.stderr)
        return 1
    if not args.version:
        try:
            with open(os.path.join(args.results, "version.txt"), encoding="utf-8") as f:
                args.version = f.readline().strip()
        except OSError:
            pass
    help_lists = {svc: parse_help(os.path.join(args.results, f"help-{svc}.txt")) for svc in SERVICES}
    matrix = build_matrix(cases, help_lists)

    npass = sum(1 for c in cases if c["status"] == "PASS")
    nfail = len(cases) - npass
    print(f"awscli: {npass} passed, {nfail} failed ({len(cases)} cases); CLI {args.version}")
    for svc, rows in matrix.items():
        cnt = collections.Counter(st for _, st, _ in rows)
        print(f"  {svc:6s} {len(rows):3d} commands: {cnt['passed']} passed, {cnt['failed']} failed, "
              f"{cnt['expected-unsupported']} expected-unsupported, {cnt['not exercised']} not exercised")
    if args.markdown:
        write_markdown(args.markdown, cases, matrix, help_lists, args)
        print(f"wrote {args.markdown}")
    if nfail:
        print(f"\n{nfail} FAILED case(s):")
        for c in cases:
            if c["status"] != "PASS":
                print(f"  {c['name']} ({c['svc']} {c['cmd']}, {c['kind']}): {c['detail']}")
        return 1
    print("\nall cases passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
